/**
 * App State Manager
 * Handles URL params, history, navigation intercepts (data-jump-to), and ghost files.
 */

export class StateManager {
    constructor(appInstance, iframe, alertUi) {
        this.app = appInstance;
        this.iframe = iframe;
        this.alertUi = alertUi;
        
        this.init();
    }

    init() {
        if (!this.iframe) return;

        // Hook into Iframe load to inject jump intercepts and check 404
        this.iframe.addEventListener('load', () => this.onIframeLoad());
    }

    onIframeLoad() {
        try {
            const doc = this.iframe.contentDocument;
            const win = this.iframe.contentWindow;

            if (!doc || !win) return;
            
            // Check for Ghost File (404/Not Found generated by our Server.js)
            const bodyText = doc.body.textContent || "";
            if (bodyText.includes("File not found:")) {
                this.handleGhostFile();
                return;
            }

            // Inject Navigation Intercept (The "Jump" Protocol)
            doc.addEventListener('click', (e) => {
                const target = e.target.closest('[data-jump-to]');
                if (target) {
                    e.preventDefault();
                    const targetIndex = parseInt(target.getAttribute('data-jump-to'), 10);
                    
                    if (targetIndex === this.app.manifest.currentIndex) {
                        // Refresh if jumping to self
                        this.app.refreshFrame();
                    } else if (!isNaN(targetIndex)) {
                        // Notify parent App
                        this.app.loadDesign(targetIndex);
                    }
                }
            });

            // Focus Trap Release (return focus to viewer when clicking outside inputs in iframe)
            doc.addEventListener('click', (e) => {
                if (['INPUT', 'TEXTAREA', 'SELECT'].includes(e.target.tagName)) return;
                // If it's a bare click on the page, force focus back to parent window
                // so keyboard shortcuts still work.
                window.focus();
            });

        } catch (e) {
            // Likely cross-origin iframe. Ignore intercepts.
        }
    }

    handleGhostFile() {
        const current = this.app.manifest.getCurrentEntry();
        const expected = current ? current.filePath : 'Unknown File';
        this.app.showDevAlert(`Ghost File: Could not locate /${expected}`);
        
        // Provide standard 404 visually in iframe
        if (this.iframe.contentDocument) {
            this.iframe.contentDocument.body.innerHTML = `
                <div style="font-family: sans-serif; display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background:#fee2e2; color:#991b1b; text-align:center;">
                    <h1>File Not Found</h1>
                    <p style="margin-bottom: 24px;">Expected file at: <code>/${expected}</code></p>
                    <button id="skip-btn" style="padding:12px 24px; background:#ef4444; color:#fff; border:none; border-radius:6px; cursor:pointer;">Ignore and Skip</button>
                </div>
            `;
            
            const btn = this.iframe.contentDocument.getElementById('skip-btn');
            if (btn) {
                btn.addEventListener('click', () => {
                    const next = this.app.manifest.getNextIndex();
                    if (next !== null) this.app.loadDesign(next);
                });
            }
        }
    }

    updateUrlParams(index) {
        if ('URLSearchParams' in window) {
            const url = new URL(window.location);
            url.searchParams.set('p', index);
            window.history.replaceState({ index }, '', url.toString());
        }
    }
}
